pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: plattform/futar
  DOCKER_BUILDKIT: 1

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        set -x
        sha=$(git rev-parse --short HEAD)
        echo "##vso[task.setvariable variable=sha]$sha"
        branch=$(git rev-parse --abbrev-ref HEAD)
        echo "##vso[task.setvariable variable=branch]$branch"
        timestamp=$(date --iso=minute)
        echo "##vso[task.setvariable variable=timestamp]$timestamp"
  - task: GoTool@0
    inputs:
      version: '1.23.3'
  - task: Go@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      command: 'get'
      arguments: '-d'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        make gen
  - task: Go@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      command: 'build'
      # -X main.version=$(branch)
      arguments: -ldflags="-X main.date=$(timestamp) -X main.commit=$(sha)"
  - task: CopyFiles@2
    inputs:
      Contents: 'futar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: futar

  - task: Docker@2
    inputs:
      repository: $(imageName)
      command: buildAndPush
      containerRegistry: DevOps_trumfops_ContainerRegistry
      tags: |
        $(Build.BuildId)
        latest
