openapi: 3.1.0
info:
  title: Demo Api
  description: Demo Api
  version: 1.0.0

paths:
  /:
    get:
      operationId: HelloWorld
      responses:
        200:
          description: Hello World

  /meta/ready:
    get:
      tags:
        - meta
      summary: ""
      operationId: MetaReady
      responses:
        200:
          description: Service is ready
        500:
          description: Error while checking readiness
        503:
          description: Service is unavailable
          headers:
            Retry-After:
              description: Indicates how long the client should wait to retry the request
              schema:
                type: number

  /meta/health:
    get:
      tags:
        - meta
      summary: ""
      operationId: MetaHealth
      responses:
        200:
          description: Service health
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceHealth"
        500:
          description: Error while checking health
        503:
          description: Service is unavailable
          headers:
            Retry-After:
              description: Indicates how long the client should wait to retry the request
              schema:
                type: number

  /meta/healthz:
    get:
      tags:
        - meta
      summary: ""
      operationId: MetaHealthz
      responses:
        200:
          description: Healthy

components:
  schemas:
    ServiceHealth:
      type: object
      properties:
        serviceName:
          type: string
        environmentName:
          type: string
        checks:
          type: array
          items:
            $ref: "#/components/schemas/ServiceHealthCheck"

    ServiceHealthCheck:
        type: object
        properties:
          name:
            type: string
          status:
            $ref: "#/components/schemas/ServiceHealthStatus"
          message:
            type: string

    ServiceHealthStatus:
      type: string
      enum: [ Ok, Degraded, Error ]
